version: '3'

services:
  mongo-db:
    image: mongo
    ports: ["27017:27017"]
    volumes:
      - ~/data_clone:/data/db mongo
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /usr/share/elasticsearch/data
    ports:
      - 9200:9200